### ISSUE TITLE
破坏 Travis CI

### ISSUE THREAD

**Issue by ivysrono** [eight04/linkify-plus-plus#15]
https://travis-ci.org/EFForg/https-everywhere/jobs/406111831#L584

正常：
![default](https://user-images.githubusercontent.com/2649544/43182464-0cb13d3a-9014-11e8-98c1-4466abafe6db.png)

LPP：
![default](https://user-images.githubusercontent.com/2649544/43182686-f51dfff4-9014-11e8-972f-58c164f12105.png)

这里面将链接转换为内嵌图片尤其不合适。

**Comment by eight04** [comment]
https://greasyfork.org/zh-TW/forum/discussion/21003/x

我自己是使用以下的 CSS 讓 Travis 能正常顯示︰
```css
/* ==UserStyle==
@name           [Travis CI] Linkify Plus Plus style
@namespace      github.com/openstyles/stylus
@version        0.1.0
@description    A new userstyle
@author         Me
==/UserStyle== */
@-moz-document domain("travis-ci.org") {
  .log-body .log-line .linkifyplus {
    margin: 0;
    position: static;
    color: inherit;
    text-decoration: underline;
  }
  .log-body .log-line .linkifyplus::before {
    content: none;
    counter-increment: none;
  }
}
```
