### ISSUE TITLE
Mark linkified urls with a custom color or similar

### ISSUE THREAD

**Issue by allo-** [eight04/linkify-plus-plus#17]
It would be nice, when linkified urls would be marked as being linkified.

I once had a userscript, which used some css like

    .linkified::before {
        content: "~";
        color: red;
    }

Some markup like this would be nice.

**Comment by eight04** [comment]
Linkified URLs have a special class `.linkifyplus`, so you can use following CSS:
```css
.linkifyplus::before {
    content: "~";
    color: red;
}
```

Also, if you point on the link, it would show a "Linkify Plus Plus" tooltip.
