### ISSUE TITLE
Change color or not color at all

### ISSUE THREAD

**Issue by darlopvil** [eight04/linkify-plus-plus#61]
Hello,

I'm having some trouble with this script when it comes to see the linkified link. It's colored as deep-dark blue and it makes it almost impossible to recognize what it says.
Example:
![imagen](https://github.com/eight04/linkify-plus-plus/assets/60988792/75306d9c-7dc7-42e2-ad47-cd739d589664)

I've also checked this issue, and it seems to be previously discussed here as #17 but i haven't found anything like `.linkifyplus::before` in the script: 
![imagen](https://github.com/eight04/linkify-plus-plus/assets/60988792/8320bacb-e44d-4b4d-afdc-35fe2a7d7bfd)

So i don't have an idea of what i can do to properly see links. Any rec?

Cheers.

**Comment by eight04** [comment]
You need a custom theme that supports link color on the page.

You can install a userstyle manager like [Stylus](https://addons.mozilla.org/en-US/firefox/addon/styl-us/). One may already make a theme for your website. Otherwise you can write your own CSS to color the link such as:

```css
/* ==UserStyle==
@name           badasstorrents.com
@namespace      github.com/openstyles/stylus
@version        1.0.0
@description    A new userstyle
@author         Me
==/UserStyle== */

@-moz-document domain("badasstorrents.com") {
  .linkifyplus {
    color: white;
  }
}
```
